export const properties = [
  {
    id: "1",
    title: "Cozy Cottage",
    price: 250000,
    images: ["/images/cottage.webp"],
    location: "Countryside",
    status: "available" as const,
    specs: {
      beds: 3,
      baths: 2,
      area: 1500,
    },
  },
  {
    id: "2",
    title: "Modern Apartment",
    price: 450000,
    images: ["/images/modern-apartment.webp"],
    location: "City Center",
    status: "pending" as const,
    specs: {
      beds: 2,
      baths: 2,
      area: 1200,
    },
  },
  {
    id: "3",
    title: "Spacious Villa",
    price: 850000,
    images: ["/images/spacious-villa.webp"],
    location: "Suburbs",
    status: "sold" as const,
    specs: {
      beds: 5,
      baths: 4,
      area: 3500,
    },
  },
  {
    id: "4",
    title: "Urban Loft",
    price: 550000,
    images: ["/images/modern-apartment.webp"],
    location: "Downtown",
    status: "available" as const,
    specs: {
      beds: 2,
      baths: 1,
      area: 1100,
    },
  },
  {
    id: "5",
    title: "Beachside Bungalow",
    price: 650000,
    images: ["/images/cottage.webp"],
    location: "Coastal Area",
    status: "pending" as const,
    specs: {
      beds: 3,
      baths: 2,
      area: 1800,
    },
  },
  {
    id: "6",
    title: "Mountain Cabin",
    price: 300000,
    images: ["/images/spacious-villa.webp"],
    location: "Mountain Region",
    status: "available" as const,
    specs: {
      beds: 4,
      baths: 3,
      area: 2200,
    },
  },
  {
    id: "7",
    title: "Luxury Penthouse",
    price: 1250000,
    images: ["/images/modern-apartment.webp"],
    location: "City Center",
    status: "sold" as const,
    specs: {
      beds: 4,
      baths: 4,
      area: 4000,
    },
  },
  {
    id: "8",
    title: "Suburban Home",
    price: 350000,
    images: ["/images/cottage.webp"],
    location: "Suburbs",
    status: "available" as const,
    specs: {
      beds: 3,
      baths: 2,
      area: 1600,
    },
  },
  {
    id: "9",
    title: "Downtown Studio",
    price: 220000,
    images: ["/images/modern-apartment.webp"],
    location: "Downtown",
    status: "pending" as const,
    specs: {
      beds: 1,
      baths: 1,
      area: 600,
    },
  },
  {
    id: "10",
    title: "Country Estate",
    price: 950000,
    images: ["/images/spacious-villa.webp"],
    location: "Countryside",
    status: "sold" as const,
    specs: {
      beds: 6,
      baths: 5,
      area: 5000,
    },
  },
  {
    id: "11",
    title: "Eco-friendly Home",
    price: 400000,
    images: ["/images/cottage.webp"],
    location: "Green Suburbs",
    status: "available" as const,
    specs: {
      beds: 3,
      baths: 2,
      area: 1700,
    },
  },
  {
    id: "12",
    title: "Historic Townhouse",
    price: 600000,
    images: ["/images/modern-apartment.webp"],
    location: "Historic District",
    status: "pending" as const,
    specs: {
      beds: 4,
      baths: 3,
      area: 2400,
    },
  },
  {
    id: "13",
    title: "Luxury Villa",
    price: 1500000,
    images: ["/images/spacious-villa.webp"],
    location: "Beachfront",
    status: "available" as const,
    specs: {
      beds: 5,
      baths: 4,
      area: 3800,
    },
  },
  {
    id: "14",
    title: "Charming Farmhouse",
    price: 500000,
    images: ["/images/cottage.webp"],
    location: "Rural Area",
    status: "sold" as const,
    specs: {
      beds: 4,
      baths: 3,
      area: 2100,
    },
  },
  {
    id: "15",
    title: "City Condo",
    price: 480000,
    images: ["/images/modern-apartment.webp"],
    location: "City Center",
    status: "available" as const,
    specs: {
      beds: 2,
      baths: 2,
      area: 1100,
    },
  },
];
